import { join } from "node:path";

import { z } from "zod/mini";

import { SKILL_FILE_NAME } from "../../constants/general.js";
import {
  OPENCODE_GLOBAL_SKILL_DIR_PATH,
  OPENCODE_GLOBAL_SKILLS_DIR_PATH,
  OPENCODE_SKILL_DIR_PATH,
  OPENCODE_SKILLS_DIR_PATH,
} from "../../constants/opencode-paths.js";
import { RULESYNC_SKILLS_RELATIVE_DIR_PATH } from "../../constants/rulesync-paths.js";
import { ValidationResult } from "../../types/ai-dir.js";
import { formatError } from "../../utils/error.js";
import { RulesyncSkill, RulesyncSkillFrontmatterInput, SkillFile } from "./rulesync-skill.js";
import {
  ToolSkill,
  ToolSkillForDeletionParams,
  ToolSkillFromDirParams,
  ToolSkillFromRulesyncSkillParams,
  ToolSkillSettablePaths,
} from "./tool-skill.js";

export const OpenCodeSkillFrontmatterSchema = z.looseObject({
  name: z.string(),
  description: z.string(),
  // OpenCode's SKILL.md parser recognizes exactly five frontmatter fields:
  // `name`, `description`, `license`, `compatibility`, and `metadata`.
  // See https://opencode.ai/docs/skills.md
  license: z.optional(z.string()),
  compatibility: z.optional(z.looseObject({})),
  metadata: z.optional(z.looseObject({})),
  // `allowed-tools` is NOT recognized by OpenCode (it is an Anthropic-spec
  // field that OpenCode silently ignores). It is kept as an optional
  // passthrough purely for lossless round-trip with the rulesync frontmatter.
  "allowed-tools": z.optional(z.array(z.string())),
});

export type OpenCodeSkillFrontmatter = z.infer<typeof OpenCodeSkillFrontmatterSchema>;

export type OpenCodeSkillParams = {
  outputRoot?: string;
  relativeDirPath?: string;
  dirName: string;
  frontmatter: OpenCodeSkillFrontmatter;
  body: string;
  otherFiles?: SkillFile[];
  validate?: boolean;
  global?: boolean;
};

export class OpenCodeSkill extends ToolSkill {
  constructor({
    outputRoot = process.cwd(),
    relativeDirPath = OPENCODE_SKILLS_DIR_PATH,
    dirName,
    frontmatter,
    body,
    otherFiles = [],
    validate = true,
    global = false,
  }: OpenCodeSkillParams) {
    super({
      outputRoot,
      relativeDirPath,
      dirName,
      mainFile: {
        name: SKILL_FILE_NAME,
        body,
        frontmatter: { ...frontmatter },
      },
      otherFiles,
      global,
    });

    if (validate) {
      const result = this.validate();
      if (!result.success) {
        throw result.error;
      }
    }
  }

  static getSettablePaths({ global = false }: { global?: boolean } = {}): ToolSkillSettablePaths {
    // OpenCode's canonical directory is the plural `skills/`. The singular
    // `skill/` is kept as an alternative search root so existing projects that
    // were generated by older rulesync versions (or hand-authored with the
    // legacy singular name, which OpenCode still loads for backwards
    // compatibility) continue to import correctly.
    return {
      relativeDirPath: global ? OPENCODE_GLOBAL_SKILLS_DIR_PATH : OPENCODE_SKILLS_DIR_PATH,
      alternativeSkillRoots: [global ? OPENCODE_GLOBAL_SKILL_DIR_PATH : OPENCODE_SKILL_DIR_PATH],
    };
  }

  getFrontmatter(): OpenCodeSkillFrontmatter {
    const result = OpenCodeSkillFrontmatterSchema.parse(this.requireMainFileFrontmatter());
    return result;
  }

  getBody(): string {
    return this.mainFile?.body ?? "";
  }

  validate(): ValidationResult {
    if (this.mainFile === undefined) {
      return {
        success: false,
        error: new Error(`${this.getDirPath()}: ${SKILL_FILE_NAME} file does not exist`),
      };
    }
    const result = OpenCodeSkillFrontmatterSchema.safeParse(this.mainFile.frontmatter);
    if (!result.success) {
      return {
        success: false,
        error: new Error(
          `Invalid frontmatter in ${this.getDirPath()}: ${formatError(result.error)}`,
        ),
      };
    }

    return { success: true, error: null };
  }

  toRulesyncSkill(): RulesyncSkill {
    const frontmatter = this.getFrontmatter();
    const opencodeBlock = {
      ...(frontmatter["allowed-tools"] !== undefined && {
        "allowed-tools": frontmatter["allowed-tools"],
      }),
      ...(frontmatter.license !== undefined && { license: frontmatter.license }),
      ...(frontmatter.compatibility !== undefined && {
        compatibility: frontmatter.compatibility,
      }),
      ...(frontmatter.metadata !== undefined && { metadata: frontmatter.metadata }),
    };
    const rulesyncFrontmatter: RulesyncSkillFrontmatterInput = {
      name: frontmatter.name,
      description: frontmatter.description,
      targets: ["*"],
      ...(Object.keys(opencodeBlock).length > 0 && { opencode: opencodeBlock }),
    };

    return new RulesyncSkill({
      outputRoot: this.outputRoot,
      relativeDirPath: RULESYNC_SKILLS_RELATIVE_DIR_PATH,
      dirName: this.getDirName(),
      frontmatter: rulesyncFrontmatter,
      body: this.getBody(),
      otherFiles: this.getOtherFiles(),
      validate: true,
      global: this.global,
    });
  }

  static fromRulesyncSkill({
    outputRoot = process.cwd(),
    rulesyncSkill,
    validate = true,
    global = false,
  }: ToolSkillFromRulesyncSkillParams): OpenCodeSkill {
    const rulesyncFrontmatter = rulesyncSkill.getFrontmatter();
    const opencodeSection = rulesyncFrontmatter.opencode;

    // `RulesyncSkillFrontmatterSchema` is a `looseObject`, so top-level
    // `license`/`compatibility`/`metadata` may exist as runtime keys even
    // though they are not part of the typed input. Read them safely here.
    const looseTopLevel = rulesyncFrontmatter as Record<string, unknown>;
    const topLevelLicense =
      typeof looseTopLevel.license === "string" ? looseTopLevel.license : undefined;
    const topLevelCompatibility =
      typeof looseTopLevel.compatibility === "object" && looseTopLevel.compatibility !== null
        ? (looseTopLevel.compatibility as Record<string, unknown>)
        : undefined;
    const topLevelMetadata =
      typeof looseTopLevel.metadata === "object" && looseTopLevel.metadata !== null
        ? (looseTopLevel.metadata as Record<string, unknown>)
        : undefined;

    // Source precedence: the `opencode` section value takes priority, falling
    // back to the top-level rulesync frontmatter value when present.
    const license = opencodeSection?.license ?? topLevelLicense;
    const compatibility = opencodeSection?.compatibility ?? topLevelCompatibility;
    const metadata = opencodeSection?.metadata ?? topLevelMetadata;

    const opencodeFrontmatter: OpenCodeSkillFrontmatter = {
      name: rulesyncFrontmatter.name,
      description: rulesyncFrontmatter.description,
      ...(license !== undefined && { license }),
      ...(compatibility !== undefined && { compatibility }),
      ...(metadata !== undefined && { metadata }),
      ...(opencodeSection?.["allowed-tools"] !== undefined && {
        "allowed-tools": opencodeSection["allowed-tools"],
      }),
    };

    const settablePaths = OpenCodeSkill.getSettablePaths({ global });

    return new OpenCodeSkill({
      outputRoot,
      relativeDirPath: settablePaths.relativeDirPath,
      dirName: rulesyncSkill.getDirName(),
      frontmatter: opencodeFrontmatter,
      body: rulesyncSkill.getBody(),
      otherFiles: rulesyncSkill.getOtherFiles(),
      validate,
      global,
    });
  }

  static isTargetedByRulesyncSkill(rulesyncSkill: RulesyncSkill): boolean {
    const targets = rulesyncSkill.getFrontmatter().targets;
    return targets.includes("*") || targets.includes("opencode");
  }

  static async fromDir(params: ToolSkillFromDirParams): Promise<OpenCodeSkill> {
    const loaded = await this.loadSkillDirContent({
      ...params,
      getSettablePaths: OpenCodeSkill.getSettablePaths,
    });

    const result = OpenCodeSkillFrontmatterSchema.safeParse(loaded.frontmatter);
    if (!result.success) {
      const skillDirPath = join(loaded.outputRoot, loaded.relativeDirPath, loaded.dirName);
      throw new Error(
        `Invalid frontmatter in ${join(skillDirPath, SKILL_FILE_NAME)}: ${formatError(result.error)}`,
      );
    }

    return new OpenCodeSkill({
      outputRoot: loaded.outputRoot,
      relativeDirPath: loaded.relativeDirPath,
      dirName: loaded.dirName,
      frontmatter: result.data,
      body: loaded.body,
      otherFiles: loaded.otherFiles,
      validate: true,
      global: loaded.global,
    });
  }

  static forDeletion({
    outputRoot = process.cwd(),
    relativeDirPath,
    dirName,
    global = false,
  }: ToolSkillForDeletionParams): OpenCodeSkill {
    return new OpenCodeSkill({
      outputRoot,
      relativeDirPath,
      dirName,
      frontmatter: { name: "", description: "" },
      body: "",
      otherFiles: [],
      validate: false,
      global,
    });
  }
}
