// Per-feature tool-target tuples; `ALL_TOOL_TARGETS` is their union (tool-targets.ts).
// Keep this a leaf module (no imports) so feature processors can import their tuple
// without a cycle through `ToolTarget`.

export const rulesProcessorToolTargetTuple = [
  "agentsmd",
  "aiassistant",
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "augmentcode",
  "augmentcode-legacy",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cursor",
  "deepagents",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "pi",
  "qwencode",
  "replit",
  "roo",
  "rovodev",
  "takt",
  "vibe",
  "warp",
  "devin",
  "zed",
] as const;

export const ignoreProcessorToolTargetTuple = [
  "aiassistant",
  "antigravity-cli",
  "augmentcode",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "cursor",
  "goose",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "qwencode",
  "roo",
  "devin",
  "vibe",
  "warp",
  "zed",
] as const;

export const mcpProcessorToolTargetTuple = [
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "augmentcode",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cursor",
  "deepagents",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "junie",
  "opencode",
  "qwencode",
  "reasonix",
  "roo",
  "rovodev",
  "vibe",
  "warp",
  "devin",
  "zed",
] as const;

export const commandsProcessorToolTargetTuple = [
  "agentsmd",
  "antigravity-ide",
  "augmentcode",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "cursor",
  "factorydroid",
  "goose",
  "hermesagent",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "pi",
  "qwencode",
  "roo",
  "takt",
  "devin",
] as const;

export const subagentsProcessorToolTargetTuple = [
  "kilo",
  "agentsmd",
  "augmentcode",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cursor",
  "deepagents",
  "devin",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "junie",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "qwencode",
  "roo",
  "rovodev",
  "takt",
  "vibe",
] as const;

export const skillsProcessorToolTargetTuple = [
  "agentsmd",
  "agentsskills",
  "aiassistant",
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "augmentcode",
  "claudecode",
  "claudecode-legacy",
  "cline",
  "codexcli",
  "copilot",
  "copilotcli",
  "cursor",
  "deepagents",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "junie",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "pi",
  "qwencode",
  "replit",
  "roo",
  "rovodev",
  "takt",
  "vibe",
  "warp",
  "devin",
  "zed",
] as const;

export const hooksProcessorToolTargetTuple = [
  "antigravity-cli",
  "antigravity-ide",
  "kilo",
  "cursor",
  "claudecode",
  "codexcli",
  "copilot",
  "copilotcli",
  "opencode",
  "factorydroid",
  "goose",
  "hermesagent",
  "deepagents",
  "kiro",
  "kiro-cli",
  "devin",
  "augmentcode",
  "junie",
  "vibe",
  "qwencode",
] as const;

export const permissionsProcessorToolTargetTuple = [
  "amp",
  "antigravity-cli",
  "antigravity-ide",
  "augmentcode",
  "claudecode",
  "cline",
  "codexcli",
  "cursor",
  "factorydroid",
  "goose",
  "grokcli",
  "hermesagent",
  "kilo",
  "kiro",
  "kiro-cli",
  "kiro-ide",
  "opencode",
  "qwencode",
  "rovodev",
  "takt",
  "vibe",
  "warp",
  "zed",
] as const;

export const ALL_TOOL_TARGET_TUPLES = [
  rulesProcessorToolTargetTuple,
  ignoreProcessorToolTargetTuple,
  mcpProcessorToolTargetTuple,
  commandsProcessorToolTargetTuple,
  subagentsProcessorToolTargetTuple,
  skillsProcessorToolTargetTuple,
  hooksProcessorToolTargetTuple,
  permissionsProcessorToolTargetTuple,
] as const;
