name: Configure git
description: Configure git user name and email
runs:
  using: composite
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name dyoshikawa
        git config user.email dyoshikawa1993@gmail.com
